### PR TITLE
Explicit property implementation fix.

### LINKED ISSUE #4: Issue when using explicitly implemented interface
When you create an interface such as

``` c#
	interface IFoo
	{
		string Bar { get; set; }
		string Baz { get; set; }
	}
```

and create a class implementing the IFoo and IFreezable interfaces such as

``` c#
	class FooImpl : IFoo, IFreezable
	{
		bool _isFrozen;

		string IFoo.Bar { get; set; }
		public string Baz { get; set; }

		public void Freeze()
		{
			_isFrozen = true;
		}
	}
```

the generated code becomes

``` c#
	internal class FooImpl : IFoo, IFreezable
	{
		private volatile bool _isFrozen;

		string IFoo.Bar { get; set; }

		public string Baz
		{
			[CompilerGenerated]
			get
			{
				return this.<Baz>k__BackingField;
			}
			[CompilerGenerated]
			set
			{
				this.CheckIfFrozen();
				this.<Baz>k__BackingField = value;
			}
		}

		public void Freeze()
		{
			this._isFrozen = true;
		}

		protected void CheckIfFrozen()
		{
			if (this._isFrozen)
			{
				throw new InvalidOperationException("Attempted to modify a frozen instance");
			}
		}
	}
```

As you can see, when using an explicitly implemented property, the CheckIfFrozen call is not added to the set method on the Bar property.

So, the following code would not throw the exception

``` c#
	void Test()
	{
		IFoo foo = new FooImpl
		{
			Bar = "bar",
			Baz = "baz"
		};
		(foo as IFreezable)?.Freeze();
		foo.Bar = "buzz";
	}
```

I'm guessing this is done because the property has a private scope, but is there a way to be able to check if the property is explicitly implementing an interface and add the CheckIfFrozen call?

### PR DESCRIPTION
**Pull request by jasonwoods-7**
PR to fix #4.

### CODE REVIEW

File: Fody/TypeProcessor.cs [hunk 1]
```diff
@@ -33,7 +33,7 @@ public void Execute()
             {
                 continue;
             }
-            if (setMethod.IsPrivate)
+            if (setMethod.IsPrivate && -1 == property.Name.IndexOf('.'))
```
Comment (SimonCropp) [inline Fody/TypeProcessor.cs]: can we have a `!Contains` here. just a little more readable

**Comment by jasonwoods-7** [comment]
No problem. Done.
